# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.left_wave_start.frame dummy
scoreboard objectives add aj.left_wave_end.frame dummy
scoreboard objectives add aj.left_wave_loop.frame dummy