# Generated by Animated Java. Modified by TophatMan__

data merge entity @e[type=item_display,tag=benAnim.LeftArm.Lower,limit=1] {transformation: [0.44066749739873223f,-0.160540202866255f,0.0f,0.4721551521496913f,-0.160540202866255f,-0.44066749739873223f,0f,1.6202506230490492f,0.0f,-0.0f,-0.469f,0.0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data merge entity @e[type=item_display,tag=benAnim.LeftArm.Middle,limit=1] {transformation: [0.44066749739873223f,-0.160540202866255f,0.0f,0.3918850507165637f,-0.160540202866255f,-0.44066749739873223f,0f,1.3999168743496828f,0.0f,-0.0f,-0.469f,0.0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data merge entity @e[type=item_display,tag=benAnim.LeftArm.Upper,limit=1] {transformation: [0.44066749739873223f,-0.160540202866255f,0.0f,0.31161494928343625f,-0.160540202866255f,-0.44066749739873223f,0f,1.1795831256503169f,0.0f,-0.0f,-0.469f,0.0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
schedule function benanim:wave/loop/02 1t replace
