# Generated by Animated Java. Modified by TophatMan__

data merge entity @e[type=item_display,tag=benAnim.LeftArm.Lower,limit=1] {transformation: [0.3317329677464069f,-0.3315331629115877f,0.0f,0.6003998721836908f,-0.3315331629115877f,-0.3317329677464069f,0f,1.538549725809805f,0.0f,-0.0f,-0.469f,0.0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data merge entity @e[type=item_display,tag=benAnim.LeftArm.Middle,limit=1] {transformation: [0.3317329677464069f,-0.3315331629115877f,0.0f,0.4346332907278968f,-0.3315331629115877f,-0.3317329677464069f,0f,1.3726832419366015f,0.0f,-0.0f,-0.469f,0.0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data merge entity @e[type=item_display,tag=benAnim.LeftArm.Upper,limit=1] {transformation: [0.3317329677464069f,-0.3315331629115877f,0.0f,0.268866709272103f,-0.3315331629115877f,-0.3317329677464069f,0f,1.2068167580633982f,0.0f,-0.0f,-0.469f,0.0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
schedule function benanim:wave/loop/03 1t replace
