# Generated by Animated Java. Modified by TophatMan__

data merge entity @e[type=item_display,tag=benAnim.LeftArm.Lower,limit=1] {transformation: [0.3014673889429869f,-0.35927484382280067f,0.0f,0.6212061328671006f,-0.35927484382280067f,-0.3014673889429869f,0f,1.51585054170724f,0.0f,-0.0f,-0.469f,0.0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data merge entity @e[type=item_display,tag=benAnim.LeftArm.Middle,limit=1] {transformation: [0.3014673889429869f,-0.35927484382280067f,0.0f,0.44156871095570005f,-0.35927484382280067f,-0.3014673889429869f,0f,1.3651168472357467f,0.0f,-0.0f,-0.469f,0.0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data merge entity @e[type=item_display,tag=benAnim.LeftArm.Upper,limit=1] {transformation: [0.3014673889429869f,-0.35927484382280067f,0.0f,0.26193128904429974f,-0.35927484382280067f,-0.3014673889429869f,0f,1.2143831527642532f,0.0f,-0.0f,-0.469f,0.0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
schedule function benanim:wave/loop/04 1t replace
