# Generated by Animated Java. Modified by TophatMan__

data merge entity @e[type=item_display,tag=benAnim.LeftArm.Lower,limit=1] {transformation: [0.45301921252957295f,-0.12138613215308214f,0.0f,0.44278959911481164f,-0.12138613215308214f,-0.45301921252957295f,0f,1.6295144093971796f,0.0f,-0.0f,-0.469f,0.0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data merge entity @e[type=item_display,tag=benAnim.LeftArm.Middle,limit=1] {transformation: [0.45301921252957295f,-0.12138613215308214f,0.0f,0.3820965330382705f,-0.12138613215308214f,-0.45301921252957295f,0f,1.4030048031323932f,0.0f,-0.0f,-0.469f,0.0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data merge entity @e[type=item_display,tag=benAnim.LeftArm.Upper,limit=1] {transformation: [0.45301921252957295f,-0.12138613215308214f,0.0f,0.32140346696172944f,-0.12138613215308214f,-0.45301921252957295f,0f,1.1764951968676067f,0.0f,-0.0f,-0.469f,0.0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
schedule function benanim:wave/loop/00 1t replace
