# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:animation/animations/left_wave_loop/zzz/apply_frame {frame: 6}
scoreboard players add @s aj.left_wave_loop.frame 1