# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.animation.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
function #animated_java:animation/as_root/pre_tick
execute if entity @s[tag=aj.animation.animation.left_wave_start.playing] run function animated_java:animation/animations/left_wave_start/zzz/on_tick
execute if entity @s[tag=aj.animation.animation.left_wave_end.playing] run function animated_java:animation/animations/left_wave_end/zzz/on_tick
execute if entity @s[tag=aj.animation.animation.left_wave_loop.playing] run function animated_java:animation/animations/left_wave_loop/zzz/on_tick
execute at @s on passengers run tp @s ~ ~ ~ ~ ~
function #animated_java:animation/as_root/post_tick