# Generated by Animated Java. Modified by TophatMan__

data merge entity @e[type=item_display,tag=benAnim.LeftArm.Lower,limit=1] {transformation: [0.4223657549344464f,-0.20388273359619027f,0.0f,0.5046620501971427f,-0.20388273359619027f,-0.4223657549344464f,0f,1.6065243162008347f,0.0f,-0.0f,-0.469f,0.0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data merge entity @e[type=item_display,tag=benAnim.LeftArm.Middle,limit=1] {transformation: [0.4223657549344464f,-0.20388273359619027f,0.0f,0.40272068339904754f,-0.20388273359619027f,-0.4223657549344464f,0f,1.3953414387336114f,0.0f,-0.0f,-0.469f,0.0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data merge entity @e[type=item_display,tag=benAnim.LeftArm.Upper,limit=1] {transformation: [0.4223657549344464f,-0.20388273359619027f,0.0f,0.3007793166009524f,-0.20388273359619027f,-0.4223657549344464f,0f,1.1841585612663883f,0.0f,-0.0f,-0.469f,0.0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
schedule function benanim:wave/end/02 1t replace
