# Generated by Animated Java. Modified by TophatMan__

data merge entity @e[type=item_display,tag=benAnim.LeftArm.Lower,limit=1] {transformation: [0.07273053055493232f,-0.46332631041761274f,0.0f,0.6992447328132096f,-0.46332631041761274f,-0.07273053055493232f,0f,1.3442978979161992f,0.0f,-0.0f,-0.469f,0.0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data merge entity @e[type=item_display,tag=benAnim.LeftArm.Middle,limit=1] {transformation: [0.07273053055493232f,-0.46332631041761274f,0.0f,0.46758157760440305f,-0.46332631041761274f,-0.07273053055493232f,0f,1.307932632638733f,0.0f,-0.0f,-0.469f,0.0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data merge entity @e[type=item_display,tag=benAnim.LeftArm.Upper,limit=1] {transformation: [0.07273053055493232f,-0.46332631041761274f,0.0f,0.23591842239559674f,-0.46332631041761274f,-0.07273053055493232f,0f,1.2715673673612669f,0.0f,-0.0f,-0.469f,0.0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
schedule function benanim:wave/end/04 1t replace
