# Generated by Animated Java. Modified by TophatMan__

data merge entity @e[type=item_display,tag=benAnim.LeftArm.Lower,limit=1] {transformation: [-0.4607427252535189f,-0.08761929653883527f,0.0f,0.41746447240412643f,-0.08761929653883527f,0.4607427252535189f,0f,0.9441929560598608f,-0.0f,-0.0f,-0.469f,0.0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data merge entity @e[type=item_display,tag=benAnim.LeftArm.Middle,limit=1] {transformation: [-0.4607427252535189f,-0.08761929653883527f,0.0f,0.3736548241347088f,-0.08761929653883527f,0.4607427252535189f,0f,1.1745643186866204f,-0.0f,-0.0f,-0.469f,0.0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data merge entity @e[type=item_display,tag=benAnim.LeftArm.Upper,limit=1] {transformation: [-0.4607427252535189f,-0.08761929653883527f,0.0f,0.32984517586529116f,-0.08761929653883527f,0.4607427252535189f,0f,1.4049356813133798f,-0.0f,-0.0f,-0.469f,0.0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
schedule function benanim:wave/end/07 1t replace
