# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animation.bone.rightleg_lower] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_rightleg_lower set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animation.bone.rightleg_middle] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_rightleg_middle set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animation.bone.rightleg_upper] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_rightleg_upper set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animation.bone.leftleg_lower] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_leftleg_lower set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animation.bone.leftleg_middle] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_leftleg_middle set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animation.bone.leftleg_upper] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_leftleg_upper set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animation.bone.chest_middleright] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_chest_middleright set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animation.bone.chest_upperleft] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_chest_upperleft set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animation.bone.chest_lowerleft] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_chest_lowerleft set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animation.bone.chest_middleleft] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_chest_middleleft set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animation.bone.chest_upperright] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_chest_upperright set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animation.bone.chest_lowerright] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_chest_lowerright set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animation.bone.leftarm_upper] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_leftarm_upper set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animation.bone.leftarm_lower] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_leftarm_lower set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animation.bone.leftarm_middle] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_leftarm_middle set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animation.bone.rightarm_lower] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_rightarm_lower set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animation.bone.rightarm_middle] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_rightarm_middle set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animation.bone.rightarm_upper] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_rightarm_upper set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animation.bone.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_head set from storage aj:uuid main.out