# Generated by Animated Java. Modified by TophatMan__

data merge entity @e[type=item_display,tag=benAnim.LeftArm.Lower,limit=1] {transformation: [-0.469f,0f,0.0f,0.35175f,0f,0.469f,0f,0.938f,-0.0f,0f,-0.469f,0.0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data merge entity @e[type=item_display,tag=benAnim.LeftArm.Middle,limit=1] {transformation: [-0.469f,0f,0.0f,0.35175f,0f,0.469f,0f,1.1725f,-0.0f,0f,-0.469f,0.0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data merge entity @e[type=item_display,tag=benAnim.LeftArm.Upper,limit=1] {transformation: [-0.469f,0f,0.0f,0.35175f,0f,0.469f,0f,1.407f,-0.0f,0f,-0.469f,0.0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
schedule function benanim:wave/start/01 1t replace
