# Generated by Animated Java. Modified by TophatMan__

data merge entity @e[type=item_display,tag=benAnim.LeftArm.Lower,limit=1] {transformation: [-0.3833181353902435f,-0.2702373162258442f,0.0f,0.5544279871693831f,-0.2702373162258442f,0.3833181353902435f,0f,1.0022613984573172f,-0.0f,-0.0f,-0.469f,0.0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data merge entity @e[type=item_display,tag=benAnim.LeftArm.Middle,limit=1] {transformation: [-0.3833181353902435f,-0.2702373162258442f,0.0f,0.419309329056461f,-0.2702373162258442f,0.3833181353902435f,0f,1.1939204661524392f,-0.0f,-0.0f,-0.469f,0.0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data merge entity @e[type=item_display,tag=benAnim.LeftArm.Upper,limit=1] {transformation: [-0.3833181353902435f,-0.2702373162258442f,0.0f,0.2841906709435389f,-0.2702373162258442f,0.3833181353902435f,0f,1.385579533847561f,-0.0f,-0.0f,-0.469f,0.0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
schedule function benanim:wave/start/03 1t replace
