# Generated by Animated Java. Modified by TophatMan__

data merge entity @e[type=item_display,tag=benAnim.LeftArm.Lower,limit=1] {transformation: [-0.190169971055876f,-0.4287148027635706f,0.0f,0.6732861020726779f,-0.4287148027635706f,0.190169971055876f,0f,1.147122521708093f,-0.0f,-0.0f,-0.469f,0.0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data merge entity @e[type=item_display,tag=benAnim.LeftArm.Middle,limit=1] {transformation: [-0.190169971055876f,-0.4287148027635706f,0.0f,0.45892870069089253f,-0.4287148027635706f,0.190169971055876f,0f,1.242207507236031f,-0.0f,-0.0f,-0.469f,0.0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data merge entity @e[type=item_display,tag=benAnim.LeftArm.Upper,limit=1] {transformation: [-0.190169971055876f,-0.4287148027635706f,0.0f,0.24457129930910726f,-0.4287148027635706f,0.190169971055876f,0f,1.3372924927639689f,-0.0f,-0.0f,-0.469f,0.0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
schedule function benanim:wave/start/04 1t replace
