# Generated by Animated Java. Modified by TophatMan__

data merge entity @e[type=item_display,tag=benAnim.LeftArm.Lower,limit=1] {transformation: [0.30031432252176504f,-0.36023923674177044f,0.0f,0.6219294275563279f,-0.36023923674177044f,-0.30031432252176504f,0f,1.5149857418913237f,0.0f,-0.0f,-0.469f,0.0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data merge entity @e[type=item_display,tag=benAnim.LeftArm.Middle,limit=1] {transformation: [0.30031432252176504f,-0.36023923674177044f,0.0f,0.44180980918544255f,-0.36023923674177044f,-0.30031432252176504f,0f,1.3648285806304412f,0.0f,-0.0f,-0.469f,0.0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data merge entity @e[type=item_display,tag=benAnim.LeftArm.Upper,limit=1] {transformation: [0.30031432252176504f,-0.36023923674177044f,0.0f,0.26169019081455736f,-0.36023923674177044f,-0.30031432252176504f,0f,1.2146714193695587f,0.0f,-0.0f,-0.469f,0.0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
schedule function benanim:wave/start/06 1t replace
