# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.animation.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'animation', 'function_path': 'animated_java:animation/animations/left_wave_end/next_frame'}
execute if score @s aj.left_wave_end.frame matches 8.. run scoreboard players set @s aj.left_wave_end.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.left_wave_end.frame
execute at @s run function animated_java:animation/animations/left_wave_end/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.left_wave_end.frame 1