# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.animation.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'animation', 'function_path': 'animated_java:animation/animations/left_wave_start/play'}
tag @s add aj.animation.animation.left_wave_start.playing
scoreboard players set @s aj.left_wave_start.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:animation/animations/left_wave_start/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only